// Generated by map.mjs. Do not edit by hand.
window.WARP_ANCHORS = [[0,0],[20,19.2],[60,48],[90,67.2],[130,96],[160,115.2],[190,139.2],[225,158.4],[240.4,168],[244,171.6]];
window.VIDEO_LENGTH = 244;
window.CREDIT = '영상 · Claude Code 로 만들었어요 · 음악은 싸이 – 아버지 원곡을 따로 틀어 주세요';
