// Re-times the father video (../src/ch, drawn for our own 2:52 song) to PSY's "아버지", to be
// watched against your own copy of that track. Nothing is redrawn: each frame of this video
// shows the frame of the original video at warp(t), where warp maps the start of every section
// of our song onto where the same part of the story should fall in "아버지".
//
// The times on the left are ESTIMATES of the published track, not read from its audio. If a
// section starts somewhere else in your copy, change its number, run `node gajang/psy/map.mjs`,
// and render again (see ../README.md).
//
//   node gajang/psy/map.mjs    -> gajang/psy/map.js

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

// [seconds into "아버지", seconds into our video]
export const ANCHORS = [
  [0, 0],          // the dark flats, the 5:30 alarm, the title
  [20, 19.2],      // first verse: mirror, kids, subway, office
  [60, 48.0],      // first chorus: desk, the weight on his shoulders, soju
  [90, 67.2],      // second verse: the boss's sigh, the stamp, the bills, overtime, the last train
  [130, 96.0],     // second chorus: the hero in the train window, the hill, the moon
  [160, 115.2],    // the bridge: twenty with a guitar, the mirror, the door, "아빠!"
  [190, 139.2],    // last chorus: the Han River, the family, the race
  [225, 158.4],    // the ending: asleep on the sofa, the city of windows
  [240.4, 168.0],  // the end card
  [244, 171.6],
];
export const LENGTH = ANCHORS[ANCHORS.length - 1][0];

writeFileSync(join(dirname(fileURLToPath(import.meta.url)), 'map.js'),
  `// Generated by map.mjs. Do not edit by hand.\nwindow.WARP_ANCHORS = ${JSON.stringify(ANCHORS)};\nwindow.VIDEO_LENGTH = ${LENGTH};\n`
  + `window.CREDIT = '영상 · Claude Code 로 만들었어요 · 음악은 싸이 – 아버지 원곡을 따로 틀어 주세요';\n`);
console.log(`wrote map.js: ${ANCHORS.length} anchors, ${LENGTH}s`);
