// A map of Billie Eilish's "bad guy" for timing pictures to it. There is no music here: the
// video is silent, made to be played against your own copy of the track (see ../README.md).
//
// These times are estimates of the published track (135 BPM, then the slow ending), not read
// from the audio. If your copy lines up differently, fix the numbers here, run
// `node badguy/song/map.mjs`, and re-render: every chapter reads its times from src/song.js.
//
//   node badguy/song/map.mjs    -> badguy/src/song.js

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

export const BPM = 135;
export const BEAT = 60 / BPM;
export const BAR = BEAT * 4;
/** Where the first downbeat falls in your copy of the track (seconds). */
export const OFFSET = 0;
/** Where the song drops into its slow ending, and how fast that is. */
export const SLOW_AT = 147.0;
export const SLOW_BPM = 67.5;
export const LENGTH = 194.0;

const at = bar => OFFSET + bar * BAR;

// Sections, in bars of the 135 BPM part (the slow ending is in seconds).
export const SECTIONS = [
  { id: 'verse1', name: '1절', t: at(0), end: at(16) },
  { id: 'pre1', name: '프리', t: at(16), end: at(24) },
  { id: 'drop1', name: '드롭', t: at(24), end: at(34) },
  { id: 'verse2', name: '2절', t: at(34), end: at(48) },
  { id: 'pre2', name: '프리', t: at(48), end: at(56) },
  { id: 'drop2', name: '드롭', t: at(56), end: at(66) },
  { id: 'break', name: '브레이크', t: at(66), end: SLOW_AT },
  { id: 'slow', name: '느린 엔딩', t: SLOW_AT, end: LENGTH },
];

// The hits the picture should land on.
export const CUES = [
  { kind: 'drop', t: at(24) }, { kind: 'drop', t: at(56) },
  { kind: 'slow', t: SLOW_AT }, { kind: 'end', t: LENGTH - 4 },
];

const song = {
  bpm: BPM, beat: BEAT, bar: BAR, length: LENGTH, offset: OFFSET,
  slow: { t: SLOW_AT, bpm: SLOW_BPM, beat: 60 / SLOW_BPM },
  sections: SECTIONS, cues: CUES, lines: [], chords: [],
};
writeFileSync(join(ROOT, 'src', 'song.js'),
  `// Generated by song/map.mjs. Do not edit by hand.\nwindow.SONG = ${JSON.stringify(song)};\n`);
console.log('wrote src/song.js', SECTIONS.map(s => `${s.id} ${s.t.toFixed(2)}`).join(' | '));
