// Cuts the Shorts' minute out of the full render: the audio from FROM_BAR to the end, and
// src/song.js with every time moved so the Short starts at 0 (still on the same beat grid,
// since FROM_BAR is a whole bar).
//
//   node shorts/song/cut.mjs      (after: node song/synth.mjs shorts/song/score.mjs)

import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as S from './score.mjs';
import { ffmpegPath } from '../../tools/ffmpeg.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const from = S.barTime(S.FROM_BAR), len = S.LENGTH - from;
execFileSync(ffmpegPath(), ['-y', '-loglevel', 'error', '-ss', from.toFixed(4), '-t', len.toFixed(4),
  '-i', join(ROOT, 'out', 'song.wav'), '-af', 'afade=t=in:d=0.02', '-c:a', 'aac', '-b:a', '192k',
  join(ROOT, 'assets', 'song.m4a')]);
const page = S.forPage();
const shift = o => ({ ...o, t: +(o.t - from).toFixed(4), ...(o.end !== undefined ? { end: +(o.end - from).toFixed(4) } : {}) });
const song = {
  ...page, length: +len.toFixed(4), fromBar: S.FROM_BAR,
  sections: page.sections.filter(s => s.end > from).map(shift),
  chords: page.chords.filter(c => c.t >= from).map(shift),
  cues: page.cues.filter(c => c.t >= from).map(shift),
};
writeFileSync(join(ROOT, 'src', 'song.js'),
  `// Generated by song/cut.mjs. Do not edit by hand.\nwindow.SONG = ${JSON.stringify(song)};\n`);
console.log(`cut ${len.toFixed(2)}s from bar ${S.FROM_BAR}`, song.sections.map(s => `${s.id} ${s.t}`).join(' | '));
console.log('cues', song.cues.map(c => `${c.kind} ${c.t}`).join(' | '));
