// Cuts the Short's bars out of the full render: the audio from FROM_BAR to TO_BAR (plus a short
// fade-out tail), and src/song.js with every time moved so the Short starts at 0.
//
//   node rescene/song/cut.mjs      (after: node song/synth.mjs rescene/song/score.mjs)

import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as S from './score.mjs';
import { ffmpegPath } from '../../tools/ffmpeg.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const from = S.barTime(S.FROM_BAR), to = S.barTime(S.TO_BAR), len = to - from + S.TAIL;
execFileSync(ffmpegPath(), ['-y', '-loglevel', 'error', '-ss', from.toFixed(4), '-t', len.toFixed(4),
  '-i', join(ROOT, 'out', 'song.wav'),
  '-af', `afade=t=in:d=0.02,afade=t=out:st=${(to - from).toFixed(4)}:d=${S.TAIL}`,
  '-c:a', 'aac', '-b:a', '192k', join(ROOT, 'assets', 'song.m4a')]);
const page = S.forPage();
const inside = o => o.t >= from && o.t < to;
const shift = o => ({ ...o, t: +(o.t - from).toFixed(4), ...(o.end !== undefined ? { end: +(Math.min(o.end, to) - from).toFixed(4) } : {}) });
const song = {
  ...page, length: +len.toFixed(4), fromBar: S.FROM_BAR,
  sections: page.sections.filter(s => s.t < to && (s.end ?? to) > from).map(shift),
  chords: page.chords.filter(inside).map(shift),
  cues: page.cues.filter(inside).map(shift),
};
writeFileSync(join(ROOT, 'src', 'song.js'),
  `// Generated by song/cut.mjs. Do not edit by hand.\nwindow.SONG = ${JSON.stringify(song)};\n`);
console.log(`cut ${len.toFixed(2)}s, bars ${S.FROM_BAR}-${S.TO_BAR}`, song.sections.map(s => `${s.id} ${s.t}`).join(' | '));
console.log('cues', song.cues.map(c => `${c.kind} ${c.t}`).join(' | '));
